"""Browsable HTML summary of a client's dumped pages."""

from datetime import datetime, timezone
from html import escape
from typing import Dict, List

_STYLE = """
body { font-family: -apple-system, sans-serif; margin: 2rem; color: #1a1a1a; }
h1 { margin-bottom: 0.25rem; }
.meta { color: #555; margin-bottom: 1.5rem; }
.warnings { background: #fff3cd; border: 1px solid #f0c36d; border-radius: 6px;
  padding: 1rem 1.25rem; margin-bottom: 1.5rem; }
.warnings ul { margin: 0.5rem 0 0; padding-left: 1.25rem; }
table { border-collapse: collapse; width: 100%; }
th, td { text-align: left; padding: 0.4rem 0.75rem; border-bottom: 1px solid #ddd;
  font-size: 0.9rem; vertical-align: top; }
th { background: #f5f5f5; position: sticky; top: 0; }
tr.empty { background: #fff3f3; }
.badge { display: inline-block; padding: 0.1rem 0.5rem; border-radius: 4px;
  font-size: 0.8rem; font-weight: 600; }
.badge.empty { background: #f8d7da; color: #842029; }
.badge.ok { background: #d1e7dd; color: #0f5132; }
code { background: #f0f0f0; padding: 0.1rem 0.3rem; border-radius: 3px; }
"""


def render_summary_html(client_name: str, label: str, pages: Dict[str, dict], warnings: List[str]) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    warnings_html = ""
    if warnings:
        items = "".join(f"<li>{escape(w)}</li>" for w in warnings)
        warnings_html = f'<div class="warnings"><strong>{len(warnings)} warning(s)</strong><ul>{items}</ul></div>'

    rows_html = []
    for path in sorted(pages):
        row = pages[path]
        is_empty = not (row.get("post_content") or "").strip()
        badge = (
            '<span class="badge empty">empty</span>'
            if is_empty
            else '<span class="badge ok">has content</span>'
        )
        row_class = ' class="empty"' if is_empty else ""
        template = row.get("page_template") or "default"
        # No current/<path>.html is written for empty pages (dump.py), so don't
        # link to a file that doesn't exist.
        path_cell = (
            escape(path)
            if is_empty
            else f'<a href="current/{escape(path)}.html">{escape(path)}</a>'
        )
        rows_html.append(
            f"<tr{row_class}>"
            f"<td>{row['ID']}</td>"
            f"<td>{path_cell}</td>"
            f"<td><code>{escape(row.get('post_name') or '')}</code></td>"
            f"<td>{escape(row.get('post_title') or '')}</td>"
            f"<td>{escape(row.get('post_status') or '')}</td>"
            f"<td>{escape(template)}</td>"
            f"<td>{badge}</td>"
            f"<td>{escape(str(row.get('post_modified') or ''))}</td>"
            f"</tr>"
        )

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{escape(label)} — page inventory</title>
<style>{_STYLE}</style>
</head>
<body>
<h1>{escape(label)}</h1>
<p class="meta">Generated by <code>wpsync dump {escape(client_name)}</code> on {generated_at}
&middot; {len(pages)} page(s) in scope.</p>
{warnings_html}
<table>
<thead>
<tr><th>ID</th><th>Path</th><th>Slug</th><th>Title</th><th>Status</th><th>Template</th><th>Content</th><th>Modified</th></tr>
</thead>
<tbody>
{"".join(rows_html)}
</tbody>
</table>
</body>
</html>
"""
